using ICDControl.Data;
using ICDControl.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ICDControl.Logic
{
    public class IcdController
    {
        private readonly DatabaseService _db;

        public IcdController()
        {
            _db = new DatabaseService();
        }

        public User Login(string email, string password) => _db.Login(email, password);

        public void Register(string name, string email, string pass) => _db.Register(name, email, pass);

        public List<Icd> GetProjects() => _db.GetAllIcds();

        // יצירת פרויקט חדש עם הודעת דוגמה
        public void CreateProject(string name, string desc)
        {
            var icd = new Icd
            {
                Name = name,
                Description = desc,
                Version = 1.0,
                LastUpdated = DateTime.Now
            };

            // יצירת הודעת דוגמה כדי שהמבנה לא יהיה ריק
            var msg = new Message
            {
                Name = "TelemetryMsg",
                IsRx = true,
                Description = "Sample Telemetry"
            };
            msg.AddField(new DataField { Name = "Altitude", Type = "float", SizeInBits = 32 });
            msg.AddField(new DataField { Name = "Speed", Type = "double", SizeInBits = 64 });

            icd.Messages.Add(msg);
            _db.SaveIcd(icd);
        }

        // לוגיקת הייצוא לקובץ Header (.h)
        public void ExportToHeaderFile(Icd icd, string filePath)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"// ICD Generated by ICDControl System");
            sb.AppendLine($"// Project: {icd.Name}");
            sb.AppendLine($"// Version: {icd.Version}");
            sb.AppendLine($"// Date: {DateTime.Now}\n");

            sb.AppendLine("#ifndef _ICD_GENERATED_H_");
            sb.AppendLine("#define _ICD_GENERATED_H_\n");

            sb.AppendLine("// --- Structures & Messages ---");
            foreach (var msg in icd.Messages)
            {
                sb.AppendLine($"// Message: {msg.Name} (Description: {msg.Description})");
                sb.Append(msg.GenerateHeaderString(0)); // קריאה רקורסיבית ליצירת ה-struct
                sb.AppendLine();
            }

            sb.AppendLine("#endif // _ICD_GENERATED_H_");

            File.WriteAllText(filePath, sb.ToString());
        }
    }
}